### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by ZefianAlfian** [sProDev/sProDev#1]
ajarin buat gini bang, sama LAST_UPDATED nya, badge nya nyari dimana?

**Comment by sProDev** [comment]
untuk autocommit bisa dilihat workflow nya di [sini](https://github.com/sProDev/sProDev/blob/master/.github/workflows/autocommit.yml). tutorialnya saya dapet dari [sini](https://mazipan.space/membuat-commit-otomatis-ke-github). kalo badge saya cuma nyoba nyoba.
